# 데이터 실습

### numpy

In [1]:
# 라이브러리 로딩
import numpy as np 

In [2]:
# 파이썬 리스트 넘파이로 변환
a = [1, 3.14, True, 'hello']
b = np.array(a)

In [3]:
# 리스트 원소 데이터 타입 확인
print(a)
for element in a:
    print('Data type of {}'.format(element, type(element)))

[1, 3.14, True, 'hello']
Data type of 1
Data type of 3.14
Data type of True
Data type of hello


In [5]:
#중첩 리스트 생성
a = [[1, 2, 3], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [6]:
# 중첩리스트 데이터 타입 확인
type(a)

list

In [7]:
# 중첩리스트를 넘파이 배열로 변환 > 2차원 행렬로
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# 행렬 데이터 타입 확인
type(b)

numpy.ndarray

In [9]:
# 배열의 shape 확인
b.shape

(2, 3)

In [10]:
#배열의 차원 확인
b.ndim

2

In [11]:
b.size

6

In [12]:
# 2*3 행렬을 3*2로 변환
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
# 배열요소 데이터 타입 변경: 정수 > 실수 0.0

b = np.array(a, dtype=np.float64)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
# 배열 요소 데이터 타입 변경 실수>정수
b = b.astype(np.int64)
print(b)

[[1 2 3]
 [4 5 6]]


### 넘파이 배열 인덱싱
 0부터 넘버링됨

In [16]:
#새로운 배열 arr생성
arr = np.array([1, 2, 3, 4, 5])

In [17]:
print(arr)

[1 2 3 4 5]


In [18]:
#배열 첫번째 원소 가져오기
print(arr[0])

1


In [19]:
#배열 네번째 원소 가져오기
print(arr[3])

4


In [20]:
# 마지막원소
print(arr[-1])

5


### 2차원 배열 인덱싱

In [21]:
#2차원 배열 생성
arr_2d = np.array([[1,2,3],[4,5,6]])

In [23]:
#1행 1열 원소 가져오기
arr_2d[0,0] # 콤마를 기준으로 행과 열을 구분

1

In [25]:
arr_2d[1,2] # 2행 3열

6

### 배열 슬라이싱

### arange 함수


In [26]:
arr_2d = np.arange(1, 7).reshape(2,3) 
#arange(시작숫자, 끝숫자): 시작숫자부터 끝숫자 -1까지의 번화가 나열되어 저장된다.
#reshape(행, 열): 원소 개수에 맞춰 reshape 을 활용하면 배열의 크기를바꿀수 있음
#활용에 따라 차원도 변경이 가능하다

In [27]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [28]:
#첫번째 행 전체 가져오기
print(arr_2d[0, :]) #첫번째 행에 대해서 모든 열의 값 출력

[1 2 3]


In [29]:
# 세번째 열 전체 출력
print(arr_2d[:, 2])

[3 6]


In [30]:
# 전체행 두번째 열까지 모두 출력
print(arr_2d[:, :2])

[[1 2]
 [4 5]]
